### ISSUE TITLE
Images and likes

### ISSUE THREAD

**Issue by mmsesay** [Lordkaito/capstone-module-2#46]
Hi team, we do love the way you structure your project and the code which is really brief and clean.
Nevertheless, there are few issues we found and below is a list

- We suggest you give the images the same height and width
- We also suggest you use a flex so that the item title and the heart icon can be inline next to each other

Finally, good job guys. Kudos.

**Comment by Whoistolu** [comment]
## Hello @mmsesay ,
Thank you for your feedback.
Changes will be implemented a soon as possible.
